<list_view x="0"  y="0" w="100%" h="100%" item_height="28">
    <scroll_view name="view" x="0"  y="0" w="-12" h="100%" children_layout="list_view(x_margin=5,spacing=10)">
      <list_item text="Test 1" /> 
      <list_item text="Test 1" /> 
      <list_item text="Test 1" /> 
      <list_item text="Test 1" /> 
      <list_item text="Test 1" /> 
      <list_item text="Test 1" /> 
      <list_item text="Test 1" /> 
      <list_item text="Test 1" /> 
      <list_item text="Test 1" /> 
      <list_item text="Test 1" /> 
    </scroll_view>
    <scroll_bar_d name="bar" x="right" y="0" w="12" h="100%" value="0"/>
</list_view>
<button focusable="true" x="c" y="m" w="30" h="30" text="x" on:click="back()"/>
